services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - uptime-kuma-data:/app/data
    networks:
      - red-cba

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxy-manager
    restart: always
    ports:
      - "80:80" #Http
      - "81:81" #Administración de la API
      - "443:443" #Https
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt

  servidor-bd:
    image: mysql:8.0
    container_name: servidor-bd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - red-cba

  app-backend:
    build: .
    container_name: app-backend
    restart: always
    volumes:
      - .:/home/myapp
    environment:
      FLASK_ENV: development
      MYSQL_HOST: servidor-bd
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "5050:5050"
    networks:
      - red-cba
    depends_on:
      - servidor-bd

networks:
  red-cba:
    name: red-cba

volumes:
  mysql-data:
    name: mysql-data
  uptime-kuma-data:
    name: uptime-kuma-data
